# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049ed97a97e7eba735be7465f1aee0f1d71bd49d5b19f00792431dc4c8e88bc09a8ac96e293791d6e3c44b59e5997ece2b1f89b321c1944e502a804856ad7869

test:
  secret_key_base: 0c7260e2653c3cd216df03c708cdf44339a8ca1bdda7d737d4c8db5b9f989af26c136eafe89136a47a84ae8b3557d0dda15735e7f5f45847bc1b1211c3bb1a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
